dikdortgenkısakenar= float(input("Kısa kenarı giriniz: "))
dikdortgenuzunkenar= float(input("Uzun kenarı giriniz: "))
cevre= (dikdortgenkısakenar * 2) + (dikdortgenuzunkenar * 2)
alan=(dikdortgenkısakenar * dikdortgenuzunkenar)
print(str("Çevresi: " + str(cevre) + "," + "Alanı: " + str(alan)))